name: Multi-step workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: simple-npm-project
        run: npm install

      - name: Run unit tests
        working-directory: simple-npm-project
        run: npm test

      - name: Style checks
        working-directory: simple-npm-project
        run: npm run style
