name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: simple-npm-project
        run: npm install

      - name: Run Jest tests
        working-directory: simple-npm-project
        run: npm test

      # Create artifact
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: simple-npm-project/test-results # Change this to the directory containing your test results

